@startuml
component Package108
component Package61
component Package104
component Package67
component Package78
component Package51
component Package75
component Package69
component Package118
component Package2
component Package88
component Package84
component Package63
component Package25
component Package113
component Package96
component Package19
component Package86
component Package72
component Package103
component Package47
component Package102
component Package59
component Package71
component Package106
component Package56
component Package27
component Package24
component Package7
component Package76
component Package86
component Package52
component Package119
component Package56
component Package65
component Package18
component Package54
component Package16
component Package87
component Package119
component Package70
component Package93
component Package7
component O-Package
Package108 --> Package108
Package108 --> Package65
Package108 --> Package54
Package108 --> Package47
Package108 --> Package63
Package108 --> Package78
Package108 --> Package84
Package108 --> Package86
Package108 --> Package106
Package108 --> Package104
Package108 --> Package18
Package108 --> Package7
Package108 --> Package88
Package108 --> Package96
Package108 --> Package113
Package61 --> Package65
Package61 --> Package108
Package61 --> Package54
Package104 --> Package108
Package104 --> Package65
Package104 --> Package86
Package67 --> Package108
Package67 --> Package54
Package67 --> Package65
Package78 --> Package108
Package78 --> Package2
Package78 --> Package19
Package78 --> Package24
Package78 --> Package70
Package78 --> Package75
Package51 --> Package108
Package75 --> Package108
Package75 --> Package72
Package69 --> Package108
Package69 --> Package65
Package69 --> Package86
Package118 --> Package108
Package118 --> Package65
Package2 --> Package108
Package88 --> Package108
Package84 --> Package108
Package84 --> Package84
Package84 --> Package65
Package63 --> Package108
Package25 --> Package108
Package113 --> Package65
Package113 --> Package113
Package96 --> Package65
Package96 --> Package108
Package19 --> Package108
Package19 --> Package16
Package86 --> Package108
Package86 --> Package65
Package86 --> Package86
Package86 --> Package102
Package72 --> Package108
Package103 --> Package65
Package103 --> Package102
Package47 --> Package65
Package102 --> Package108
Package59 --> Package108
Package71 --> Package108
Package71 --> Package71
Package106 --> Package65
Package56 --> Package108
Package27 --> Package65
Package24 --> Package108
Package7 --> Package65
Package7 --> Package7
Package7 --> Package108
Package76 --> Package108
Package86 --> Package108
Package86 --> Package65
Package86 --> Package86
Package52 --> Package108
Package52 --> Package65
Package119 --> Package65
Package56 --> Package65
Package65 --> Package108
Package65 --> Package65
Package65 --> Package86
Package65 --> Package87
Package65 --> Package93
Package65 --> Package118
Package65 --> Package7
Package65 --> Package71
Package65 --> Package25
Package65 --> Package27
Package65 --> Package119
Package65 --> Package54
Package65 --> Package52
Package65 --> Package51
Package65 --> Package61
Package65 --> Package59
Package65 --> Package69
Package65 --> Package67
Package65 --> Package76
Package65 --> Package56
Package65 --> Package84
Package65 --> Package106
Package65 --> Package102
Package65 --> Package103
Package18 --> Package65
Package18 --> Package108
Package54 --> Package65
Package54 --> Package108
Package54 --> Package51
Package54 --> Package54
Package54 --> Package56
Package16 --> Package108
Package87 --> Package65
Package119 --> Package119
Package70 --> Package108
Package93 --> Package65
Package7 --> Package65
@enduml